import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'tw-elements-react/dist/css/tw-elements-react.min.css';
import './globals.css';

import { Roboto } from 'next/font/google';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <section className='h-full bg-neutral-200 dark:bg-neutral-700'>
          <div className='container mx-auto h-full px-10 py-5'>{children}</div>
        </section>
      </body>
    </html>
  );
}
